#!/bin/sh

BRANCH=${1:-master}

echo "  About to watch '$BRANCH'"
echo "    please have inotifywait and git..."

git checkout -b ${BRANCH} 2> /dev/null

git checkout ${BRANCH}

inotifywait -m ./ -e CLOSE_WRITE |
  while read path action file; do
    echo "$path" "$action" "$file"

    git add .
    git commit --no-gpg-sign -m "auto-commit"
    git push origin ${1:-master}
  done